[[100 ошибок в Go и как их избежать]]

Ошибки в defer нужно тоже обрабатывать или хотя бы явно игнорировать. Но что если мы хотим вернуть ошибку, которая возникла в `defer`?
```go
defer func() {
	closeErr := rows.Close()
	if err != nil {
		if closeErr != nil {
			log.Printf("failed to close rows: %v", err)
		} 
		return
	}
	err = closeErr
}()
```
Для этого нужно использовать именованные параметры в return. 